# Generated by Django 4.2.1 on 2023-07-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(blank=True, null=True, verbose_name='Основная')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Тематики статьи',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('articles', models.ManyToManyField(related_name='rubrics', through='articles.ArticleRubric', to='articles.article')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='articlerubric',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AddField(
            model_name='articlerubric',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='articles.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterUniqueTogether(
            name='articlerubric',
            unique_together={('article', 'rubric')},
        ),
    ]
